CREATE OR ALTER FUNCTION dbo.udf_GetSKUPrice (@ID_SKU INT)
RETURNS decimal(18,2)
BEGIN
RETURN(
SELECT SUM(Value)/CAST(SUM(Quantity) AS DECIMAL(18, 2))
FROM dbo.Basket
WHERE @ID_SKU=ID_SKU
);
END;